### ISSUE TITLE
warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

### ISSUE THREAD

**Issue by Jimbobnz** [bneedhamia/sdconfigfile#6]
`C:\Users\James\Documents\Arduino\libraries\sdconfigfile\SDConfigFile.cpp:238:12: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     return "OUT OF MEMORY";`

I'm not sure how to fix this.

**Comment by bneedhamia** [comment]
Thanks for using the library, and for reporting this bug. The bug is a result of my sloppiness about char * vs. const char *. Practically speaking, it's a warning that you can ignore. I'll fix the problem the next time I work on that library.

See http://arduino.stackexchange.com/questions/13429/deprecated-conversion-from-string-constant-to-char for a detailed explanation of the problem.

Also, please post the following information to help me fix this error: Your Arduino IDE version and the Board you're compiling for. I don't see the message on Arduino IDE 1.6.7, compiling for either Uno or Mega, which makes it hard to know when I've fixed the problem.

Thanks again for reporting this bug,
Brad

**Comment by bneedhamia** [comment]
Corrected in commit 60782d1.
